jobs:
  execute:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: jpmcb/prow-github-actions@f4d01dd4b13f289014c23fe5a19878a2479cb35b
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        prow-commands: /assign /unassign /area /kind /priority /remove /close /reopen
          /lock /milestone /hold /cc /uncc
name: Issue and PR comment commands
on:
  repository_dispatch:
    types: trigger-ga___issue-command.yml
permissions: {}
