concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
jobs:
  check-links:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Get script
      run: 'wget https://raw.githubusercontent.com/xuruidong/markdown-link-checker/main/link_checker.py

        '
    - continue-on-error: true
      name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - continue-on-error: true
      name: Link check (critical, all files)
      run: '# python link_checker.py ./ --enable-external --ignore "http://apisix.iresty.com"
        "https://www.upyun.com" "https://github.com/apache/apisix/actions/workflows/build.yml/badge.svg"
        "https://httpbin.org/" "https://en.wikipedia.org/wiki/Cache"

        python link_checker.py ./

        '
name: Link Checker
on:
  repository_dispatch:
    types: trigger-ga___md-link-check.yml
permissions:
  contents: read
  pull-requests: read
