jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v5
      with:
        close-issue-label: wait-for-feedback
        close-issue-message: This issue has been automatically marked as stale because
          it hasn't had any recent activity.If you think this should still be open,
          or the problem still persists, just pop a reply in the comments and one
          of the maintainers will (try!) to follow up. Thank you for your interest
          and contribution to the Sping Cloud Alibaba Community.
        days-before-issue-close: 7
        days-before-issue-stale: 30
        days-before-pr-close: -1
        days-before-pr-stale: -1
        exempt-all-milestones: true
        exempt-issue-labels: discussion,bug,question,good first issue
        operations-per-run: 10
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stale
        stale-issue-message: This issue has been open 30 days with no activity. This
          will be closed in 7 days.
name: Stale bot of marking stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  issues: write
